### ISSUE TITLE
JÄGERMEISTER

### ISSUE THREAD

**Issue by DERTAKTISCHEDEUTSCHEFUSSPILZ** [HerrChaos/alcohol_only#3]
Jedes Mal wenn man Jägermeister trink kommt der Jägermeister clip https://youtu.be/jnhTxejPYFQ?si=3EYbAkLuit6IhtAX

**Comment by blryface** [comment]
wgar

**Comment by blryface** [comment]
Please use English

**Comment by HerrChaos** [comment]
Every time he drinks Jägermeister he gets the clip which he sent. I think he means the achievement.

**Comment by blryface** [comment]
not a bug..?
